### ISSUE TITLE
Created tracks not shown in profile

### ISSUE THREAD

**Issue by PeterKrcmar0** [somecookie/runPHARAA#187]
I created two tracks and initially they appeared when I went on my profile. However, after relaunching the app they disappeared and now it says that I created 0 tracks.

In the firebase database, the information si correct for the tracks but not for the user, so the issue is probably the way we initialize the user's created tracks when he/she logs in.

**Comment by somecookie** [comment]
I am not able to reproduce the bug with the code that is on master
